name: Build Executable

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile src/main.py  # Replace 'main.py' with your Python file name

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: dist/main.exe  # Replace 'main.exe' with the desired name of the generated executable
